-- AlterTable
ALTER TABLE "Deal" ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "cardMarketPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "margin" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Search" ALTER COLUMN "minPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "maxPrice" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "lastAvgPrice" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Settings" ALTER COLUMN "alertMinMargin" SET DATA TYPE DOUBLE PRECISION;
